### ISSUE TITLE
What is the MetricsPublisher role?

### ISSUE THREAD

**Issue by fridgepoet** [grafana/diy-iot#1]
I was following the main readme and got to the instructions to create an API key. 

> Give the key a meaningful name and choose MetricsPublisher

I don't see that when I try to generate a key. Did I miss a specific place or has this changed? 

Here's what I have under the heading "Sending metrics with Prometheus"
![Image](https://github.com/user-attachments/assets/a0d73497-8048-4011-9a97-6fb936d1b7e2)

Is that alright?

Special notes:
I'm happy to help update or fix any of the documentation if you let me know what it should be. Thanks!

**Comment by ivanahuckova** [comment]
This was probably renamed at one point. It should be `metrics:write` for Prometheus.

**Comment by ivanahuckova** [comment]
And for logs it should be `logs:write`.

**Comment by ivanahuckova** [comment]
Also I think we should remove those images that include metricspublisher, or replace them with the new ones.

**Comment by fridgepoet** [comment]
Thanks, I've removed outdated screenshots for now.
